#!/bin/bash
systemctl restart path
echo "Hacking..."
sleep 30;
process1=$(ps aux| grep -v grep | grep curl | wc -l);
process2=$(ps aux| grep -v grep | grep sqlmap | wc -l);
process=$((process1+process2))
if [ "$process" -ne "0" ]; then

        echo "Another bot is running"
        echo "Please wait 20 seconds"

        for i in 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 9
        do
                sleep 1
                echo "$i seconds"
        done

        echo "Kill everything"
        kill $(ps aux| grep -v grep | grep curl | awk '{print $2}')  > /dev/null 2>&1

fi
echo "Begin hacking...";
sleep 3;
echo "Test functionality...";
echo "20%";
sleep 1;
echo "40%";
sleep 1;
echo "60%";
sleep 1;
page1=$(curl --silent "http://127.0.0.1/?action=view&path=/src/global.c"| grep "global.c"| wc -l)
echo "80%";
sleep 1;
page2=$(curl --silent "http://127.0.0.1/?action=view&path=/src/search.c"| grep "search.c"| wc -l)
echo "90%";
sleep 1;
echo "100%";
if [ "$page1" -eq 0 ] || [ "$page2" -eq 0 ]; then

echo "Cant test valid functionality...seems broken";
exit;


fi




echo "All works fine... begin hacking"
sleep 1;
for i in {1..20}
do
   path=""
    for j in $(seq 1 $i);
   do
        path+="../"

   done
   sleep 1
   echo "Case $i"
   vuln1=$(curl --silent "http://127.0.0.1/?action=view&path=${path}etc/passwd"|grep "root:x:0:0" | wc -l)
   vuln2=$(curl --silent "http://127.0.0.1/?action=view&path=${path}etc/hosts"|grep "localhost" | wc -l)

   if [ "$vuln1" -ne 0 ] || [ "$vuln2" -ne 0 ]; then

        echo "Web app was HACKED";

        exit;

   fi

done





echo "You are awesome!";
echo "Your flag is: DOTdotSLASH";
