java -jar /home/user/bot/target/bot-1.0.jar -l liam -p someStrongAndUltraSecretpass --screenshot /home/user/liam.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l noah -p someStrongAndUltraSecretpass --screenshot /home/user/noah.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l oliver -p someStrongAndUltraSecretpass --screenshot /home/user/oliver.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l elijah -p someStrongAndUltraSecretpass --screenshot /home/user/elijah.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l william -p someStrongAndUltraSecretpass --screenshot /home/user/william.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l james -p someStrongAndUltraSecretpass --screenshot /home/user/james.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l benjamin -p someStrongAndUltraSecretpass --screenshot /home/user/benjamin.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l lucas -p someStrongAndUltraSecretpass --screenshot /home/user/lucas.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l henry -p someStrongAndUltraSecretpass --screenshot /home/user/henry.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l alexander -p someStrongAndUltraSecretpass --screenshot /home/user/alexander.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l olivia -p someStrongAndUltraSecretpass --screenshot /home/user/olivia.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l harper -p someStrongAndUltraSecretpass --screenshot /home/user/harper.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l evelyn -p someStrongAndUltraSecretpass --screenshot /home/user/evelyn.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l mia -p someStrongAndUltraSecretpass --screenshot /home/user/mia.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l isabella -p someStrongAndUltraSecretpass --screenshot /home/user/isabella.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l amelia -p someStrongAndUltraSecretpass --screenshot /home/user/amelia.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l sophia -p someStrongAndUltraSecretpass --screenshot /home/user/sophia.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l charlotte -p someStrongAndUltraSecretpass --screenshot /home/user/charlotte.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l emma -p someStrongAndUltraSecretpass --screenshot /home/user/emma.jpg
java -jar /home/user/bot/target/bot-1.0.jar -l ava -p someStrongAndUltraSecretpass --screenshot /home/user/ava.jpg